In [1]:
import pandas as pd
df = pd.read_csv('../../data/car_sales_cleaned1.csv')
df = df.drop_duplicates()
df = df.dropna()

In [6]:
# df_hyundai = df[df['Company'] == 'Hyundai']
df_hyundai = df[df['Company'] == 'Hyundai'].reset_index()
df_hyundai

,index,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,16,Female,535000,Hyundai,Accent,Manual,Black,18000
1,124,Female,1690000,Hyundai,Sonata,Manual,Black,15000
2,168,Male,955000,Hyundai,Elantra,Manual,Pale White,26000
3,250,Male,457000,Hyundai,Sonata,Manual,Pale White,21000
4,289,Male,13500,Hyundai,Sonata,Manual,Black,20000
...,...,...,...,...,...,...,...,...
219,23248,Female,1675000,Hyundai,Sonata,Manual,Black,20500
220,23432,Female,13500,Hyundai,Elantra,Manual,Red,22000
221,23650,Female,460000,Hyundai,Sonata,Manual,Black,15000
222,23738,Male,705000,Hyundai,Sonata,Manual,Red,21000
223,23745,Male,681500,Hyundai,Accent,Manual,Black,18500

In [3]:
df_toyota = df[(df['Company'] == 'Toyota') & (df['Price ($)'] > 40000)]
df_toyota

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
239,Male,1350000,Toyota,Tacoma,Auto,Pale White,53000
258,Male,1151000,Toyota,Corolla,Auto,Pale White,41100
269,Female,825000,Toyota,Tacoma,Manual,Pale White,82000
308,Female,13500,Toyota,Corolla,Auto,Pale White,41000
358,Male,1326000,Toyota,RAV4,Manual,Black,85600
...,...,...,...,...,...,...,...
23379,Male,1300000,Toyota,Celica,Auto,Pale White,45001
23385,Female,615000,Toyota,Tacoma,Auto,Pale White,53000
23443,Male,2400000,Toyota,RAV4,Manual,Black,85000
23476,Male,520000,Toyota,Celica,Auto,Pale White,45000
23735,Male,1635000,Toyota,Tacoma,Auto,Pale White,53501

In [4]:
df['Model'].value_counts().head(3)

Model
Prizm         362
Diamante      347
Silhouette    337
Name: count, dtype: int64

In [8]:
most_popular_cars = df[['Company','Model']].value_counts().head(3) # head daet 5 pervih strok
most_popular_cars

Company     Model
Chevrolet   Prizm         362
Mitsubishi  Diamante      347
Oldsmobile  Silhouette    337
Name: count, dtype: int64